// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "PushIn.h"

PushIn::PushIn() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::subsystem1);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

// Called just before this Command runs the first time
void PushIn::Initialize() {
	if(Robot::subsystem1->doubleSolenoid1->Get() == Robot::subsystem1->doubleSolenoid1->kReverse)
		Robot::subsystem1->PushIn();
	else
		Robot::subsystem1->PushOut();

}

// Called repeatedly when this Command is scheduled to run
void PushIn::Execute() {
	
}

// Make this return true when this Command no longer needs to run execute()
bool PushIn::IsFinished() {
	return false;
}

// Called once after isFinished returns true
void PushIn::End() {
	
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void PushIn::Interrupted() {

}
